table Pedidos
	lineageTag: f9006ba8-c171-4e86-a334-d645ea7fc970

	column 'ID Pedido'
		dataType: string
		lineageTag: 4f8ab0c6-f16c-4ecb-a7e4-e90f86ada594
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Data Pedido'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 14432b3d-06b1-48f6-889f-216a46b38a7a
		summarizeBy: none
		sourceColumn: Data Pedido

		variation Variation
			isDefault
			relationship: 34100e24-15e9-4911-8e47-66a042c67d67
			defaultHierarchy: LocalDateTable_529931a1-99e2-45ba-b960-931e20324c75.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f35efe1-1d02-4dd9-8c27-ae39bf7edef2
		summarizeBy: none
		sourceColumn: Data Envio

		variation Variation
			isDefault
			relationship: 36169b3d-df17-4d8e-8efe-9be2a62de074
			defaultHierarchy: LocalDateTable_b6c694cc-a648-4a58-ba24-0a5c20181824.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Modo Envio'
		dataType: string
		lineageTag: f75c089f-3ce8-4dd0-b2e5-985c69319eaf
		summarizeBy: none
		sourceColumn: Modo Envio

		annotation SummarizationSetBy = Automatic

	column 'Prioridade Pedido'
		dataType: string
		lineageTag: b354173b-eb35-4753-9225-6fd98c36a3d9
		summarizeBy: none
		sourceColumn: Prioridade Pedido

		annotation SummarizationSetBy = Automatic

	partition Pedidos = m
		mode: import
		source =
				let
				  Origem = Csv.Document(File.Contents("C:\Users\intrigx\OneDrive\Documentos\CURSOS\POWER BI\ATIVIDADES\CAP03\Arquivos\Pedidos.csv"), [Delimiter = ";", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Cabeçalhos promovidos" = Table.PromoteHeaders(Origem, [PromoteAllScalars = true]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(#"Cabeçalhos promovidos", {{"ID Pedido", type text}, {"Data Pedido", type date}, {"Data Envio", type date}, {"Modo Envio", type text}, {"Prioridade Pedido", type text}}),
				    #"Texto Aparado" = Table.TransformColumns(#"Tipo de coluna alterado",{{"ID Pedido", Text.Trim, type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Texto Aparado")
				in
				  #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

